= Tuesday, December 14th 2016
:published_at: 2016-12-14

.Dev Ops Workshop
....
Its all about the docker image.  
Learned about working IBM GitHub and creating issues and resolving.
I'm working on setting up Tomcat 7 on Centos 7 with ssl enabled and Java 8
Had some trouble with all this since Docker is not something I know through and through
but I have a lot of experience with Linux at this point, and my VM mechanics help with getting things to work.
Hoping tomorrow I get a lot done.
....


.Chris one-one
....
.Todos
* Prioritize getting stories and tasks created and estimated
  - Get acceptance criteria done and make sure QE has enough to create test plans
* Rename UCF Connector tab to UCF Connector / RCoC Q1
* Modify team members:
  - Remove Ken as build engineer
  - Add Mark as QE
* Add one or two sprints to the project
* Identify one or two stories to get started on before leaving for Christmas break
* Questionnaire is a nice-to-have; prioritize UCF Connector
* Get UCF connector story/task into implementing state
* Review stories 52328, 52308 and 52309 to see if they can be finished off after the new REST TDI connector is implemented
* Consider adding a task for converting existing file connector-implemented stories/tasks to using the new REST TDI connector
* Update scheme task or story??

.Kick off 
* Scrum kick off meeting is set for Thursday at 4
* Talk about which stories to work on 
* Schedule stand up for two times a week and pick a day and time that works for everyone

NOTE: UCF will likely merge into the larger RCoC team

.Chris' suggestions for working with RCoC group (Rajeev and ?)
* Do quality work--there are high expectations of me coming in
* Communicate effectively and often--don't let problems queue up without letting folks know what is going on
* Rajeev is easy going, but members are emotionally vested in their product (implication is, choose my words carefully, be diplomatic)
* Provide very good input
* Keep promises 
* Sift into the mix gradually
* Don't overstretch

.Random notes from one on one meeting
* There will be one week left after vacation for sprint 2
* In betwixt all this, I need to be ready to help out if needed with OpenPages, either to offer guidance or to jump in and make fixes
....








