= July 18, 2017

*Yesterday*

Created a production build for the op-installer that combines the client, server and auth-server into one zip file with these features:

- provides its own gulp file and package.json that provides all that is needed to build (npm install) and run the application (npm start) in production mode.
- temporarily creates a default deployment so that the install UI works without manual intervention (previously had to create a test deployment by hand)

Met with Filipe, Josh and Wenlong to discuss rest api end point naming and questions concerning configuration import.

*Today*

- Have to take a few days to get the Algo group on track. 
- Meeting with Rajeev at 11 to determine the depth and breadth of my remaining tasks
- Then attending group status meeting at 11:30
- Creating/updating RTC tasks to reflect the work I've done to date on the op-installer (apologies for not keeping them up to date--will work at dillegence)
- Putting together a presentation showing the makeup of the typescript auth-server.  Will meet with the team some time either this week or next to discuss.

*Going forward*

- With the build and deployment work done, moving on to doing some op-installer UI work.  Taking on the _Choose Deployment_ page that appears after login.  Currently login takes the user to a default deployment called _testInstall_
- Will update READMEs to reflect current processes for running and deploying project
- Create some quick diagrams to show how the op-installer modules fit together to create one unit in both production and dev.  Investigate how this diagram can be displayed in the projects README.


