= Info

- Met yesterday with IP to discuss my Goals, which I have updated.  I spent my lunch doing the updates and feel that I've done a decent job of it, but of course there are always going to be things I leave out.  I need to get better about writing down my accomplishments and activities.
- We talked about B9 promotion again, but I felt like we have already been down this road before and there appears to still be a residual problem with unnamed members of my OP community, to the point that it is probably time for me to seek out other opportunities within the company.  
	- IP told me that he achieved B9 by doing something outside of his normal workday by helping the services organization with some helper applications that made their lives easier. He advises me to do something similar, going outside of my assigned job to make a difference to the company.
    - I reminded him that I did the VM and made it so anyone that needed to could get a fresh development environment in a matter of hours instead of days or weeks. He acknowleged this and really considered it, but my concern is that I need to keep reminding him and anyone else that will listen that I did this.  He agrees that my push in this area propelled the installation team to pursue UCD and Docker, and now today an environment is a few clicks away.  But in general, it feels to me that my contribution here is forgotten.
    - IP implied that I might not like it if I were to achieve B9, and talked about the Peter Principle.  I told him that I was already working at the B9 level where I came from, and that I was told that I would get there in few years once I came on board.  It turns out that John started at B9, and I'm kicking myself because I should have made it a condition of my coming into the company, but I didn't know how it works.  I told IP that I am ready and have all the confidence in the world in my ability to succeed.
    - He described the process of how the team meets to discuss who should be in line for promotions.  He told me that BS no longer rolls his eyes when IP tells him what I am working on, so BS is an impediment to my succession.  He is one but I don't know who else.  I need to ask who specifically is blocking me.  He told me that John is someone who would have an influence.
    - IP told me that there are limited B9 spots, and the company will give the ok to grant them on a limited basis.  SV was just promoted to B9, so another opportunity has come and gone.
    - I expressed my dissatisfaction with working on OP defects, that I really enjoyed the creative liberties working on the Installer.
    - What do I imagine will be the benefit of B9, he asked.  He was thinking it was a money thing.  My answer, job satisfaction.  The work I'm doing now can be done by anyone--my talents are being wasted.
    - I said that I won't be here in a year if this continues.  
    - He said I should do some presentations.  This has been said before when we discussed this when IP first took over as manager.  He had also talked about inviting me to some architect meetings with M and JO.  Never happened.  Seems like all the things we talked about pertaining to B9 promotion has been completely forgotten.  The last one-on-one when I mentioned it, he told me that all the action items are mine, but the prior one-on-one he told me that he will look into it.
    - I wrapped up by saying that I need to be given opportunity to work with the larger organization in order to achieve outside influence.  I did well with the Installer team, but IP sort of implied that nobody respects the installation team in any organization, so any contributions there would not be respected.  I asserted that I needed opportunities to shine, but working on OP defects is not it.
    
I noticed that the work on the next version of OP UI is being done by everyone around me.  On Friday last week, the group of MP, KG, JO and IP talked about it outside of my cubicle and they were excited working together and strategizing.  IP stopped by afterward, I think because he obviously knew I had heard them talking, and told me that they are pulling JH into the group, and that I would keep working on defects for a while. 

I'm clearly not part of anything and am being relegated onto side avenues while the core group creates and plans.
