= Openpages Docker Setup
:hp-tags: docker, openpages, dev, setup

http://masa-rhel11.swg.usma.ibm.com/repositories/op[OP Docker Registry]

https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/W1662f310fa3e_4801_b067_6cd1a876162b/page/Run%20OpenPages%20on%20docker[Run OpenPages on docker]

== Get OP version number for .env ==

- telnet op-dkreg-kvm01.swg.usma.ibm.com
- See http://op-dkreg-kvm01.swg.usma.ibm.com:5000/v2/op/opapp_db2/tags/list[here] in browser

Example output in browser:
```json
{
"name": "op/opapp_db2",
"tags": [
  "7.2",
  "7.2.0.1-112",
  "7.2.0.3-23",
  "7.4-161",
  "7.2.0.2-65",
  "7.3-273",
  "7.3.0.2-78"
]}
```

== Get current 7.devenv from Github ==

https://github.ibm.com/OpenPages/devops/tree/master/docker/7.devenv[Follow this link]

Create .env file from the sample.env you see in 7.devenv and make appropriate changes to the environment settings.  Here is mine:

```
# Set this tag number to your desired build number
OPVER=7.3.0.2-78

HOSTNAME=${HOSTNAME}
COMPOSE_HTTP_TIMEOUT=600
WAS_DEBUG=true
OPAPP_MANUAL_START=false

# This should be your Eclipse workspace directory
OP_WORKSPACE=/Users/sellis/projects/ibm/7.3.0.2

# Change this to the root directory of your local devops project
DEVOPS_WORKSPACE=/Users/sellis/projects/ibm/7.3.0.2/devops

# This should be the directory to which you will export EAR files from Eclipse
HOST_SHARED=/Users/sellis/virtualbox/shared
```

The 7.devenv folder has two docker-compose files, one for db2 and the other for oracle.  I only take the db2 version and rename it from docker-compose-app-db.yml to docker-compose.yml, which is the default name of a docker-compose file so that docker-compose command line commands do not need to specify the name parameter.

So to build and run the OpenPages docker image, on the command line and in the 7.devenv folder, type:

```
docker-compose up -d
```

This will take a while if doing this from scratch.

When complete, OpenPages should be accessible on your favorite browser at https://localhost:10111

== Extending OpenPages for development ==

This https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/Wa37f5439c5fa_480b_92fb_66b4f71bcc50/page/Extending%20OpenPages%20VirtualBox%20Installation%20for%20Development[wiki] post describes the process to convert your environment to one for development.

This set of commands converts all the javascript libraries in SOSA to their development (source) versions:

```bash
cd ~/projects/ibm/eclipse-mars/com.ibm.openpages.sosa/sosa
mkdir devbak
mv ./dojo_1.10.4 ./devbak/dojo_1.10.4_prod
mv ./dojo_1.8.4 ./devbak/dojo_1.8.4_prod
mv ./gridx1.2 ./devbak/gridx1.2_prod
mv ./ibmjs ./devbak/ibmjs_prod
mv ./idx_1.5.1.8 ./devbak/idx_1.5.1.8_prod 
ln -s ../../com.ibm.openpages.libraries.idx/dojo_1.10.4 dojo_1.10.4
ln -s ../../com.ibm.openpages.libraries.idx/dojo_1.8.4 dojo_1.8.4
ln -s ../../com.ibm.openpages.libraries.idx/idt_1.9/gridx_1.2 gridx1.2
ln -s ../../com.ibm.openpages.libraries.idx/idx_1.5.1.8 idx_1.5.1.8
ln -s ../../com.ibm.openpages.libraries.idx/ibmjs ibmjs
```

*Ignore all production javascript libraries*

If you choose to back up the javascript libraries as in the previously outlined step, then you will need to ignore them in Eclipse or your resource searches will have two of everything, which is incredibly annoying.  

- Open the project properties for com.ibm.openpages.sosa (cmd-I with project selected).
- Navigate to Resource->Resource Filters
- _Add Filter_
	* Filter type -> Exclude all
    * Applies to -> Folders, all children (recursive)
    * File and Folder Attributes -> Project Relative Path | matches | sosa/devbak
- _Add Filter_ in project com.ibm.openpages.libraries.idx
	* Filter type -> Exclude all
    * Applies to -> Folders, all children (recursive)
    * File and Folder Attributes -> Project Relative Path | matches | *

*Create oneui_ie.css*

In idx_1.5.1.8, there needs to be oneui_ie.css in idx/themes/oneui

These files don't exist by default, so you either get them from another environment or create them your self:

oneui_ie.css:
```css
@import url("ie_0oneui.css");
@import url("ie_1oneui.css");
```

ie_0oneui.css and ie_1oneui.css need to be obtained from somewhere else, so a todo is to put these somewhere to be retreived later.

== Generate op-apps.ear and redeploy OpenPages on Docker container ==

*Generate op-apps.ear*

- right click on grc_webapps -> op-apps
- choose Export -> EAR file
- take the ear projedt op-apps, and set the destination as the shared folder that is the location you chose for the _HOST_SHARED_ setting in your docker .env file from above.
- I check the boxes for _Export source files_ (not sure what benefit this has) and _Overwrite existing file_, which will overwrite the last ear you generated without prompting you.

*SSH into docker container*

- Unless you've changed the port numbers from the 7.devenv Dockerfile, your ssh port into the OP docker container is 24022.  Execute the command ``ssh -l opuser -p 24022 localhost`` (the default password is ``passw0rd``)
- You may encounter this:

```bash
Js-MacBook-Pro:sosa sellis$ ssh -l opuser -p 24022 localhost
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:3zXdLVc6cmYqnKxN8rHkxzH/tW8Gm+phXr/nC0Yl5Uc.
Please contact your system administrator.
Add correct host key in /Users/sellis/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/sellis/.ssh/known_hosts:57
RSA host key for [localhost]:24022 has changed and you have requested strict checking.
Host key verification failed.
```

Simply edit the known_hosts file and remove the line number specified and try again.

- Make sure you have copied the redeployEAR.sh file from the 7.devenv folder on your host OS.  Here is what I did:

```bash
cd ~/OP/OpenPages/temp/perlinstall/
cp ~/shared-devopsworkspace/docker/7.devenv/redeployEAR.sh .
```

- Execute the redeploy command: ``./redeploy.sh``
- Cross your fingers that this works -- for me it did, first time!!


-- Modify the OP URL 

On the file system, navigate to:
	- $OP_HOME/profiles/OpenPagesDmgr/config/cells/OpenPagesCell/applications/op-apps.ear/deployments/op-apps/META-INF/application.xml
    
In the https://localhost:9043/ibmconsole[Websphere Console], you can make the same change in Applications->Application Types->Websphere enterprise applications->op-apps->Web Module Properties->Context Root For Web Modules.

When exporting op-apps.ear from Eclipse, be sure to modify the deployment descriptor to remove op from the sosa.war context-root, or the login page will display but login will always result in session expired exception.  

*View OP Application logs*

- Here: /home/opuser/OP/OpenPages/profiles/opapp-OPNode1/logs/opapp-OPNode1Server1

*Change Debug Settings*

Edit _/home/opuser/OP/OpenPages/profiles/OpenPagesDmgr/config/cells/OpenPagesCell/nodes/opapp-OPNode1/servers/opapp-OPNode1Server1_ and find the section toward the the bottom that contains the text _7777_:

```
<jvmEntries 
	debugMode="true" 
 	debugArgs="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7777" 
	xmi:id="JavaVirtualMachine_1536354754418" 
	verboseModeClass="false" 
 	verboseModeJNI="false" 
 	initialHeapSize="512" 
  	maximumHeapSize="1536" 
 	runHProf="false" 
 	hprofArguments="" 
 	genericJvmArguments="-Xgcpolicy:gencon 
 		-Xmn350m -Xdisableexplicitgc 
		-Dcom.ibm.itp.location=/home/opuser/IBM/WebSphere/AppServer/bin 
		-Dopenpages.home=/home/opuser/OP/OpenPages 
		-Daurora.home=/home/opuser/OP/OpenPages/aurora 
		-Djava.security.auth.login.config=/home/opuser/OP/OpenPages/aurora/conf/aurora_auth.config 
		-Dfile.encoding=utf-8 
		-Dclient.encoding.override=UTF-8 
		-Dopenpages.instance=opapp-OPNode1Server1">
```

The first attribute is _debugMode_, which must be set to _true_ in order to connect remotely to OpenPages.
The second attribute is _debugArgs_.  Set _suspend=y_ if you would like to debug the application as it is starting up.
The application will wait until the debugger is remotely connected before proceeding to initialize.

*Manually linking sosa.war to your OpenPages development environment*

If you have started a Docker version of OpenPages and have already followed the steps for enabling OpenPages for development as described above, and you do not wish to (or encounter errors when you try to) redeploy the op-apps.ear file, you can manually create a link in the docker container to point the sosa.war file to your development environment, so that when making changes to javascript you can see those changes immediately.

This assumes that the docker image is Linux-based.

```bash
cd ~/OP/OpenPages/profiles/opapp-OPNode1/installedApps/OpenPagesCell/op-apps.ear/
~/OP/OpenPages/bin/stopAllServers.sh admin openpages
mv sosa.war sosa.war.bak
ln -s ~/shared-workspace/com.ibm.openpages.sosa/sosa/ ./sosa.war
~/OP/OpenPages/bin/startAllServers.sh
```

The first step takes you to the current OP deployment's ear folder, where the current sosa.war folder lives, which is being backed up in the third step.  
After the backup step, step 4 creates the symlink that makes a new sosa.war folder, but one that points to the sosa folder in the web project from your Eclipse workspace.


