= Typescript Conversion

*typescript-rest*

Using the typescript-rest library endpoints are activated using Spring-like annotations:

```javascript
@Path("/tapi/auth")
@Accept("application/json")
export default class AuthorizationService {
    @Path("/login")
    @POST
    login(requestUser: IUser): Promise<AuthToken> {
		...
    }
}
```

*type safety*

Typescript provides type safety at compile-time.  From the previous example, the login method receives a posted request with an IUser in the request body.  IUser is defined as such:

```javascript
export interface IUser {
  id : string;
  name : string;
  password : string;
}
```

The return type of the login method is clearly defined as well.  I know from looking at the definition that I will get back an AuthToken:

```javascript
export class AuthToken {
    id: string;
    value: string;
    expires : number;

    constructor(token : AuthToken) {
        this.id = token.id;
        this.value = token.value;
        this.expires = token.expires;
    }
}
```

*json file as database repository*

The auth-server uses the NPM module _node_flat_db_ to handle json file manipulation as a database.  The class _JsonDB_ is a generic class that can be used for any entity type that you would like to manage.  Currently the auth-server does so for authorization tokens and users.  _JsonDB_ defines CRUD operations (create, remove, update and delete), taking the entity name as a parameter:

```javascript
export default class JsonDB {
    static insert<T>(entityName, values) : Promise<T> {
        return new Promise<T>((resolve, reject) => {
        	...
        });
    }

    static update<T>(entityName, key, values) : Promise<T> {
        return new Promise<T>((resolve, reject) => {
        	...
        });
    }

    static remove(entityName, where) {
        return new Promise((resolve, reject) => {
        	...
        });
    }

    static find<T>(entityName, criteria, suppressThrowIfNotFound): Promise<T> {
        return new Promise<T>((resolve, reject) => {
        	...
        });
    }
}
```

The UserModel makes use of JsonDB to manage IUser entities:

```Javascript
import {IUser} from "../entities/IUser";
import JsonDB from "./json.db";

export default class UserModel {
    static addUser(name, password) {
        return JsonDB.insert("user", {
            name : name,
            password : password
        });
    }

    static findUser(name, password) : Promise<IUser> {
        return JsonDB.find<IUser>("user", {name : name, password : password}, true);
    }

    static findUserByName(name) : Promise<IUser> {
        return JsonDB.find<IUser>("user", {name : name}, true);
    }

    static findUserById(id) : Promise<IUser> {
        return JsonDB.find<IUser>("user", {id : id}, false);
    }
}
```

The TokenModel manages the AuthToken entity:

```javascript
import JsonDB from "./json.db";
import {AuthToken} from "../entities/index";

export default class TokenModel {
    static addUserToken(id, token) {
        return JsonDB.insert<AuthToken>("token", {id : id, value : token, expires : TokenModel.getNewExpiration()});
    }

    static findUserToken(userId) : Promise<AuthToken> {
        return JsonDB.find<AuthToken>("token", {id : userId}, true);
    }

    static getNowAsSeconds() {
        return Math.floor(Date.now() / 1000.0);
    }

    static getNewExpiration() {
        const now = TokenModel.getNowAsSeconds();
        return now + config.jwtExpirationSeconds;
    }

    static isExpired(ts) {
        const now = TokenModel.getNowAsSeconds();
        return now >= ts;
    }
}
```

*Conversion of existing server code*

The bulk of the work to convert server javascript to auth-server typescript follows along these guidelines:

- Create index.ts at the root of packages and export all module classes.  For example, in server/actions/index.ts:
```javascript
export { app_vali_action } from './app-vali-action';
export { bpm_vali_action } from './bpm-vali-action';
export { ConfigManager } from './config-manager';
export { db_vali_action } from './db-vali-action';
export { preValiAction } from './pre-vali-action';
export { rep_vali_action } from './rep-vali-action';
export { search_vali_action } from './search-vali-action';
```
This enables the ability to import all classes or select classes from module in one statement.  For example:

```javascript
import {
    Constants as constants,
    cryptoHelper,
    dbHelper,
    javaHelper,
    logger,
    osHelper,
    propertiesHelper as propHelper,
    VersionHelper,
    wasHelper
} from '../helpers/index';
```
- Convert require statements to imports.  Importing from another typescript file is as simple as ``import classname from './classname'``, but when importing non-typescript libraries, it is necessary to have this form: ``import * as path from 'path'``, which in this example is importing the Node.js library _path_.  

- 