= Long running processes in Node.js

Wenlong needs help with long running tasks kicked off by Rest API requests.  
The problem now is that processing these requests keeps a grib on the event loop with blocking IO (file IO using the sync versions) such that control of the event loop is not relinquished.  

I've introduced Promises, and that, along with the use of the aysnchronous versions of the file IO calls may do the trick, since using the asynchronous calls may give up the event loop and allow processing of a simultaneous request.

If that is not enough, then there is an interesting [library](https://github.com/soyuka/relieve) called Relieve available on NPM that spawns the handling of a task using Promises.  

Look into this tonight.  Meeting with Wenlong in the AM to discuss, so work on some examples tonight--ASAP.

Event Loop in Node.js article: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/

Interesting solution to try: https://stackoverflow.com/questions/29896854/how-to-execute-abort-long-running-tasks-in-node-js
