= UCF TDI Developer Setup =

https://www.ibm.com/support/knowledgecenter/SSFUEU_7.3.0/com.ibm.swg.ba.cognos.op_installation_guide.7.3.0.doc/c_op_ig_ucf_instl.html[Official Docs]

*Introduction*

OpenPages integrates with https://cch.commoncontrolshub.com[UCF Common Controls Hub] (referred to hereafter as CCH) to import Authority Documents, Citations and Controls using assembly lines as implemented in TDI (Tivoli Directory Integrator).  UCF stands for Unified Compliance Framework.

In a nutshell, CCH determines commonality amongst all controls across all industry authority documents and combines all of these controls into a single control, then references these common controls across all authority documents instead of duplicating them.  This greatly reduces the amount of time organizations need to spend during compliance.  Once the conditions of a control have been satisfied once, the conditions are satisfied for any and all processes that share that same control.

OpenPages has different object type names for the CCH types that are being imported.  The following list shows first the CCH type name and its OpenPages equivalent:

- Authority Document -> Mandate
- Citation -> SubMandate
- Control -> Requirement

The process of importing CCH objects into OpenPages begins with executing custom assembly lines in TDI.  To do this, you first need to install TDI on Windows.  If you are using a Mac, then this will describe how to install TDI using VirtualBox.

*The source code*

The TDI assembly line that integrates OP and CCH lives in RTC in _<workspace_root>/grc_sdi_integrations/ucf_integration_.  There you will find a README.txt that describes some of the steps that will be reproduced here.  Once TDI is installed this location will be accessed to import the assembly lines and import or update existing Mandates, SubMandates and Requirements.

*Installation*

The TDI installation files are included with the OP installation media, and can be found at _opserver.swg.usma.ibm.com/Share/TDI-7.1.1_.  The two files you will need are these:

- 7.1.1-TIV-TDI-FP0004.zip
- TDI_GP_E_V7.1.1_WIN-X86_64.zip

*VirtualBox* 

If installing on a virtual machine, be sure to create a shared folder for transferring files between the host and the virtual appliance.  On my system I created a shared folder called _shared_, and another shared folder that points to the root of the OP workspace called _openpages_.  The names are unimportant.

There are exported Windows VirtualBox VMs in _opserver.swg.usma.ibm.com/Share/Windows IE VM Images_ that can be used for the purpose of TDI development and testing.  The exported VM I use originates from the exported image _Windows 7 IE 9.ova_ from the aforementioned share folder.  Simply import that into VirtualBox as a new VM.  Be sure to configure the shared folders as described.  

*VirtualBox Network Settings* 

Also, you will need to access the internet from the VM, as you will be connecting to CCH.  You will also need to network to your OpenPages instance running on the Host OS (either directly on the Host OS or in a Docker instance).  If you are running OpenPages on a remote server via the IBM internal network, then be sure to configure a Bridged network connection.  This https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/Wa37f5439c5fa_480b_92fb_66b4f71bcc50/page/VirtualBox%20Network%20Settings%20for%20OpenPages%20Development[wiki post] describes the VirtualBox networking setup required for OpenPages development and is applicable here as long as the OpenPages installation is on the Host OS (including Docker).  Follow the directions for setting up a _Host Only_ and _NAT Network_.  A bridged adapter will give your VM an actual ip address that can be accessed anywhere on the local network, and will make available to the virtual machine other machines on the same network.

As these instructions are being written, the following network adapters have been established:

1. Adapter 1 - Bridged Adapter - attached to en4: Thunderbolt Ethernet
2. Adapter 2 - Host-only Adapter - IPv4 Address: 192.168.59.100
3. Adapter 3 - NAT Network, Network CIDR: 10.0.3.0/24

Start the Windows 7 VM and check ip configuration by typing _ipconfig_ from the powershell.  You will see three ethernet adapters, listed in reverse order from how they match up to the adapters created in the previous step.  The names of these ethernet connections are:

- _Ethernet adapter Local Area Connection_ - Bridged (Adapter 1)
- _Ethernet adapter Local Area Connection 2_ - Host-only (Adapter 2)
- _Ethernet adapter Local Area Connection 3_ - NAT Network (Adapter 3)

**Bridged Adapter**


```
ipconfig 

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : usma.ibm.com
   IPv6 Address. . . . . . . . . . . : 2620:1f7:807:870::1:17b
   IPv6 Address. . . . . . . . . . . : 2620:1f7:807:870::1:27b
   Link-local IPv6 Address . . . . . : fe80::5d4b:18ab:2000:7939%11
   IPv4 Address. . . . . . . . . . . : 9.32.70.214
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::2%11
                                       fe80::1%11
                                       9.32.70.1
```

The bridged adapter is assigned a real IPv4 address that can be accessed from any system on the network.  Test this connection by pinging it from the Host OS:

```
js-macbook-pro:7.devenv sellis$ ping 9.32.70.214
PING 9.32.70.214 (9.32.70.214): 56 data bytes
64 bytes from 9.32.70.214: icmp_seq=0 ttl=128 time=0.436 ms
64 bytes from 9.32.70.214: icmp_seq=1 ttl=128 time=0.427 ms
64 bytes from 9.32.70.214: icmp_seq=2 ttl=128 time=0.399 ms
```

If ping does not work, then you may have a firewall issue on the Windows OS.  Try turning off the firewall, or create an exception in the firewall to allow incoming requests on that address.

**Host-Only Adapter**

The host-only adapter is a private connection that allows direct access to the Windows 7 VM through a static IP address that we have decided will be _192.168.59.100_.  That's the address we assigned when we created the network adapter in VirtualBox, but the address has to also be configured directly in Windows before it will take effect.  Try _ipconfig_ now and you will see that the ip address is not what we intendip:

```
Ethernet adapter Local Area Connection 2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::9407:e95d:b7b8:405d%13
   Autoconfiguration IPv4 Address. . : 169.254.64.93
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
```

To assign the static ip address, do the following:

- Open the control panel and navigate to _Network and Sharing Center_
- Click on the link for _Local Area Connection 2_
- Press the _Properties_ button.
- Select _Internet Protocol Version 4 (TCP/IPv4)_ and click on _Properties_
- Select the radio button _Use the following IP address:_
- Enter the following:
  * ip address: _192.168.59.100_
  * subnet mask: _255.255.255.0_
  * default gateway: _192.168.59.1_
  * Leave all DNS server addresses blank
- Shut down and restart Windows

If after reboot the ip address still is not the assigned value, then type the following:

```
PS C:\Windows\system32> netsh interface ipv4 show inter

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 11          10        1500  connected     Local Area Connection
 13          10        1500  connected     Local Area Connection 2
 16          10        1500  connected     Local Area Connection 3
```

The index value of _Local Area Connection 2_ is 13, and is used in the following command that turns off autoconfiguration for that network interface:

```
netsh interface ipv4 set interface 13 dadtransmits=0 store=persistent
```

Reboot and check again with _ipconfig_:

```
Ethernet adapter Local Area Connection 2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::9407:e95d:b7b8:405d%13
   IPv4 Address. . . . . . . . . . . : 192.168.59.100
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.59.1
```

Who'd have dreamed it could be so simple?

*You should be able to ping 192.168.59.100 from the Host OS, but as I recreate the steps, something is stopping this from working.*

**NAT Network Adapter**

The NAT Network Adapter is a private connection from the Guest OS (Windows 7 in this case) to the Host OS.  This is the 3rd ethernet adapter you see in _ipconfig_:

```
Ethernet adapter Local Area Connection 3:

   Connection-specific DNS Suffix  . : usma.ibm.com
   Link-local IPv6 Address . . . . . : fe80::4899:5a41:a115:b67c%16
   IPv4 Address. . . . . . . . . . . : 10.0.3.4
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.3.1
```

I cannot explain why, but given the information above, you should be able to access web applications that are running locally on the Host OS via the ip address _10.0.3.2_.  For example, if OpenPages is running in a docker container that is accessible from a browser on the Host OS at _https://localhost:10111_, then open a browser in the Windows VM and navigate to _https://10.0.3.2:10111_.  

You should be presented with the OpenPages login screen.

**Preparing Openpages to Receive UCF Entities**

The following information is detailed in official https://www.ibm.com/support/knowledgecenter/SSFUEU_7.3.0/com.ibm.swg.ba.cognos.op_installation_guide.7.3.0.doc/c_op_ucf_cnfg_op.html[OpenPages documentation] but is reproduced here for your happy, one-stop-fun convenience.

OpenPages must have a set of business entities that are the parent objects of the UCF entities being imported.  There is also an additional object relationship that needs to be created (_SOXBusEntity_ as a parent to _Requirement_).  The following steps involve a fastmap and Object Manager.  The sources for both can be found in the _ucf_integration/Runtime-ucf_integration_ folder in the Eclipse workspace.

**Fastmap Import**

- From the legacy UI, navigate to _Reporting->Fastmap Import_
- Click on _Choose File_ and select _UCF Entities.xlsx_ from the _ucf_integration/Runtime-ucf_integration_ folder
- Click on _Import Data_
- You should see a message on the page indicating that 34 objects will be created, and 2 will be updated if they contain changes
- Click on _Import Data_ and wait for completion

To verify that the objects have indeed been created, navigate to _Organization->Business Entity Overview_.  Expand the _Library_ business entity, where you should see a new business entity called _UCF_, and beneath that _Authority Documents_ and _Harmonized Controls_, which can both be expanded to see several child entities, all of which can be the parent entities of incoming UCF objects.

**Object Manager import**

The explicit directions for this part is explained https://www.ibm.com/support/knowledgecenter/SSFUEU_7.3.0/com.ibm.swg.ba.cognos.op_installation_guide.7.3.0.doc/t_op_ucf_load_objects.html[here].

You will need to transfer the file  _ucf_integration/Runtime-ucf_integration/req-op-config.xml_ to the system where OpenPages is running, to a folder _<OP_HOME>/integrations/UCF_.  The default docker installation already has this file in that location, so there is no need to transfer the file in that scenario.  Assuming you are running OpenPages on a Docker container, then the following set of commands will get this part done:

```
ssh -l opuser -p 24022 localhost
cd ~/OP/OpenPages/bin
./ObjectManager.sh l c <admin user> <admin password> ../integrations/UCF req
```

When complete, you can verify in OpenPages that the _SOXBusEntity_ is a valid parent of a _Requirement_.

**UCF Field Groups**

You can also verify that the UCF field groups and fields have been created, but those should have already been created in recent versions of OpenPages, and won't be detailed here, other than to say the field groups have a prefix of _UCF_.

**TDI Installation**

Now that we have a Windows VM that has access to OpenPages, and OpenPages has been properly prepared to receive UCF objects, we can install TDI and run some assembly lines.

- Copy the downloaded TDI zip files to a local folder on the Windows VM and extract them. 
- In the _TDI_GP_E_V7.1.1_WIN-X86_64_ folder (created via extraction), navigate to _windows_x86_64_ and run _install_tdiv711_win_x86_64.exe_ and follow all the prompts
- After a successful installation, navigate to _7.1.1-TIV-TDI-FP0004/7.1.1-TIV-TDI-FP0004_ and follow the directions in the _7.1.1-TIV-TDI-FP0004.README_.  

**Importing the OP Assembly Lines**

- Run the TDI launcher called _Start Configuration Editor_
- Select _File->Import..._ and choose _IBM Tivoli Directory Integrator->Configuration_
- With the _File_ radio button selected, click _..._ next to the _Configuration File_ text area and navigate to the _openpages_ shared folder that was made available via the shared folders settings when we created the VM, and find _grc_sdi_integrations/ucf_integration/Runtime-ucf_integration/ucf_integration.xml_.  Click _Open_.
- Click on _Finish_ and give the project a name.  Any name will do. I chose _ucf_integration_.
- Click on _Finish_

**Authentication**

In order to access CCH we need to get authenticated.  For testing we use a corporate account, and for those credentials you will need to get them from Christophe.  There are individual accounts as well that can be obtained via the CCH support staff, but the details are fuzzy right now on how to obtain them.  It used to be that you could go to the CCH Slack channel and get it taken care of, but now things have changed.  Regardless, this one is something you'll have to work out by starting with Christophe.  

You'll need a user (which is the email address) and the associated password.  With the login, you can get into the https://cch.commoncontrolshub.com/account-login.php[CCH website] and acquire an API token from _Settings->API Manager->API Keys_.  The api key will be applied to _password.properties_ in TDI as described below.

Then you'll need the OpenPages user and password.  That should be much simpler to get.

To get the credentials into your TDI project, quit the TDI editor and copy a set of files either from your OpenPages installation or from the Eclipse workspace via the VM share.  The OP installation location comes from the same location as the _ucf_integration.xml_ file we just imported into TDI (_grc_sdi_integrations/ucf_integration/Runtime-ucf_integration_.  If you are on the VM as described here, the files can be found at _<openpages share drive letter>:\grc_sdi_integrations\ucf_integration\Runtime-ucf_integration_.

The following files should be copied into your TDI workspace root (I accepted the default location when installing TDI, and that location is _C:\Users\scottell\Documents\TDI\workspace\ucf_integration\Runtime-ucf_integration_:

- op_client.properties
- passwords.properties

Now do the following:

- After copying the files to your workspace, start TDI again.
- Navigate from the project root to Resources->Properties and edit the _op_client_ properties.  
- Set the OpenPages user name in the _Local Value_ field for _op_user_
- Modify the _op_url_ field to indicate the host ip address of the actual OP server.  In the case of the VM we've set up here, the ip address is _10.0.3.2_
- Click _Send properties to Server_
- Save the properties file (ctrl-s)
- Edit the _passwords_ properties in the same folder
- Enter a valid value for the OpenPages password in _op_password_
- Enter the UCF API token in _ucf_api_token_
- Click _Send properties to Server_
- Save the properties file (ctrl-s)

**Running the Assembly Lines**

Running the assembly lines is the final step, and if you've made it this far then you are a brave soul.  The first assembly line to run is called _UCF_Authority_Documents_to_OP_Mandates_.  Double click this assembly line in the TDI Navigator panel.

The assembly line works by acquiring a list of authority documents from CCH as identified by the API Token we applied to the _passwords_ properties.  The authority documents are chosen as only those that have been shared.  You can see this on the CCH website by navigating to _Workspace->Manage Your Saved Lists_.  Here you will see the lists that are included.  By editing a shared list, and toggling the radio button _Show Selected Documents in a Hierarchy_, you can see the complete listing of all authority documents that are part of the shared list.  

So for a quick test, choose a list with only a single, and small, authority document.  For my test I am choosing _ISO 13335-1_, authority document id: _0000084_.  I've ensured that no other list is shared, and I've created (or in this case, shared an existing) list with only this single authority document in it.

Once done, actually run the assembly line.

With the _UCF_Authority_Documents_to_OP_Mandates_ selected, click on _Run in console_ and pray for a miracle.

If your OP url is secured via https, the first attempt to run will fail with an error the looks like this:

```
15:09:19,613 ERROR - CTGDIS077I Failed with error: You must restart the SDI server in order for the imported certificate to be trusted..
```

Restart TDI and try the assembly line again.

Here is the output from a successful run:

```
15:19:23,082 INFO - Loading Authority Document List for id 6442
15:19:23,707 INFO  - CTGDIS087I Iterating.
15:19:23,722 INFO - Processing Authority Document 84, 1 of 1
15:19:35,332 INFO - OpenPages Connector version: 20160812 1050
15:19:35,347 INFO - Object is Mandate and object id is 79
15:19:35,347 INFO - The OpenPages Connector configuration properties used for this instance are:
	URL (op_url):                          https://10.0.3.2:10111/grc/api
	User Id (op_username):                 OpenPagesAdministrator
	GRC Object (op_object):                Mandate
	Query (op_query):                      null
	Parent Object Type (op_parentType):    SOXBusEntity
	Parent Object Location (op_parentLoc): 
	Debug log (op_deBug):                  false
	URI Root (op_root):                    /grc/api
	SMTP Host (smtpHost):                  
	SMTP Port (smtpPort):                  25
	Mail To (mailTo):
15:19:47,441 INFO - Using the primaryParentId value '5802' derived from the feed's parentType and parentLocation values.
15:19:48,769 INFO - Created new Mandate object named 'UCF-AD-0000084'
15:19:48,769 INFO  - CTGDIS088I Finished iterating.
15:19:48,769 INFO  - CTGDIS100I Printing the Connector statistics.
15:19:48,769 INFO  -  [UcfAuthorityDocumentFeed] Get:1
15:19:48,769 INFO  -  [Get parent business entity resource id and location] Lookup:1
15:19:48,769 INFO  -  [OpenPagesConnector] Lookup:1, Add:1
15:19:48,785 INFO  - CTGDIS104I Total: Get:1, Lookup:2, Add:1.
15:19:48,785 INFO  - CTGDIS101I Finished printing the Connector statistics.
15:19:48,785 INFO  - CTGDIS080I Terminated successfully (0 errors).
```

Run the other two assembly lines in this order:

1. UCF_Citations_to_OP_Submandates
2. UCF_Controls_to_OP_Requirements

**Development**








