= Logging Frameworks =

I am researching logging frameworks that can help with resolving customer issues quickly.
There are two aspects to consider here, one being standard logging practices, and the other being a logging framework that can assist with monitoring multiple logs simultaneously, and filtering out unwanted messages that constantly flood our logs.  

I put a question out on the cognitive architect slack channel asking what kinds of logging frameworks others are using, and I got back a reply suggesting that I take a look at https://www.splunk.com/[Splunk].

Before I dive into _Splunk_, I want to list out the other technologies that I intend to evaluate as well.

== Logging Techs ==

These aren't all necessarily solely logging technologies, but could be part of a stack of products.  These are the names that have turned up while hunting down answers to the central question of better visibility into error logs.

- https://www.elastic.co/products/logstash[Logstash]
- https://www.graylog.org/overview[Graylog]
- https://www.elastic.co/products/kibana[Kibana]
- https://www.elastic.co/products/elasticsearch[Elasticsearch]

== Splunk ==

I've downloaded _Splunk Enterprise_ and added a Splunk Docker container to my development environment docker-compose.yml.  I renamed docker-compose.yml to docker-compose-splunk.yml and added a services section to it as detailed https://github.com/dennybritz/docker-splunk/blob/master/enterprise/docker-compose.yml[here].  Here is the added services section as per the linked page:

```
volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  splunkenterprise:
    #build: .
    hostname: splunkenterprise
    image: splunk/splunk:7.0.3
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
```

For reference, to use the new docker-compose file I typed this command in the same folder:

```
docker-compose -f docker-compose-splunk.yml up -d
```

To verify that it started up correctly I typed:

```
docker logs --follow 7devenv_splunkenterprise_1
```

The successful startup information that I see as a result of the previous command is:

```
Starting splunk server daemon (splunkd)...  
Done


Waiting for web server at http://127.0.0.1:8000 to be available.... Done


If you get stuck, we're here to help.  
Look for answers here: http://docs.splunk.com

The Splunk web interface is at http://splunkenterprise:8000

Listening for Splunk data on TCP port 9997.
Listening for data on TCP port 1514.
```

From the host system, _splunkenterprise_ is not a valid host name (but is a valid host name between the docker containers that are composed together).  To see the Splunk UI, navigate to http://localhost:8000.

== Splunk Logging Options ==

If we want to add an appender to our log4j configurations, then we need to upgrade to log4j2, and that is a https://logging.apache.org/log4j/2.x/manual/migration.html[pain].  The problem in our application is that we violate some of the prerequisites for smooth migration from log4j 1.x to 2.x:

```
1. They must not access methods and classes internal to the Log4j 1.x implementation such as Appenders, LoggerRepository or Category's callAppenders method.
2. They must not programmatically configure Log4j.
3. They must not configure by calling the classes DOMConfigurator or PropertyConfigurator.
```

So guess what?  We do all of the above.  PropertyConfigurator is used in the following classes:

- ObjectManagerLocal
- ObjectProfileGenerator
- ProfileUpdateUtility
- StringKeysSearchGenerator
- StringSearchGenerator
- USSGenerator
- LogUtils
- TestAssetType
- Log4jEventLogger

DOMConfigurator is used in the following:

- LogUtils
- FrameworkGenerator

LoggerRepository is used in LogUtils

callAppenders is isued in Log4jEventLogger

We have Log4j Appenders in:

- Log4jEventLogger
- LoggerUtil
- LoggerUtilExtended
- ResourceUtil

So that's a lot of work to do for migration!


== Graylog ==

Installed docker images for Graylog as detailed http://docs.graylog.org/en/2.4/pages/installation/docker.html#here[here].  Added this to the same docker-compose-splunk.yml but should have probably done it seperately--didn't feel like making a big deal out of it.  I have both Graylog and Splunk running simultaneously now with OP.

After bringing re-composing on the docker yml, Graylog is up in a web browser at http://localhost:9000, user and password are both _admin_.

http://docs.graylog.org/en/2.4/pages/getting_started/web_console.html[Graylog setup instructions]

Getting log4j v1.2 logs from our application to Graylog appears to be doable using a custom https://logging.paluch.biz/examples/log4j-1.2.x.html[logstash-gelf appender].  The same site has this https://logging.paluch.biz/index.html[introduction].

Here is an example appender that is configured in log4j.xml:

```
<appender name="gelf" class="biz.paluch.logging.gelf.log4j.GelfLogAppender">
    <param name="Threshold" value="INFO" />
    <param name="Host" value="udp:localhost" />
    <param name="Port" value="12201" />
    <param name="Facility" value="java-test" />
    <param name="ExtractStackTrace" value="true" />
    <param name="FilterStackTrace" value="true" />
    <param name="IncludeLocation" value="true" />
    <param name="MdcProfiling" value="true" />
    <param name="TimestampPattern" value="yyyy-MM-dd HH:mm:ss,SSSS" />
    <param name="MaximumMessageSize" value="8192" />
    <param name="AdditionalFields" value="fieldName1=fieldValue1,fieldName2=fieldValue2" />
    <param name="AdditionalFieldTypes" value="fieldName1=String,fieldName2=Double,fieldName3=Long" />
    <param name="MdcFields" value="mdcField1,mdcField2" />
    <param name="DynamicMdcFields" value="mdc.*,(mdc|MDC)fields" />
    <param name="IncludeFullMdc" value="true" />
</appender>
```

I'll have to add this to OP 8.0.0.2 and see if the Graylog dashboard picks anything up.

