= UCF TDI Developer Setup =

https://www.ibm.com/support/knowledgecenter/SSFUEU_7.3.0/com.ibm.swg.ba.cognos.op_installation_guide.7.3.0.doc/c_op_ig_ucf_instl.html[Official Docs]

*Introduction*

OpenPages integrates with https://cch.commoncontrolshub.com[UCF Common Controls Hub] (referred to hereafter as CCH) to import Authority Documents, Citations and Controls using assembly lines as implemented in TDI (Tivoli Directory Integrator).  UCF stands for Unified Compliance Framework.

In a nutshell, CCH determines commonality amongst all controls across all industry authority documents and combines all of these controls into a single control, then references these common controls across all authority documents instead of duplicating them.  This greatly reduces the amount of time organizations need to spend during compliance.  Once the conditions of a control have been satisfied once, the conditions are satisfied for any and all processes that share that same control.

OpenPages has different object type names for the CCH types that are being imported.  The following list shows first the CCH type name and its OpenPages equivalent:

- Authority Document -> Mandate
- Citation -> SubMandate
- Control -> Requirement

The process of importing CCH objects into OpenPages begins with executing custom assembly lines in TDI.  To do this, you first need to install TDI on Windows.  If you are using a Mac, then this will describe how to install TDI using VirtualBox.

*The source code*

The TDI assembly line that integrates OP and CCH lives in RTC in _<workspace_root>/grc_sdi_integrations/ucf_integration_.  There you will find a README.txt that describes some of the steps that will be reproduced here.  Once TDI is installed this location will be accessed to import the assembly lines and import or update existing Mandates, SubMandates and Requirements.

*Installation*

The TDI installation files are included with the OP installation media, and can be found at _opserver.swg.usma.ibm.com/Share/TDI-7.1.1_.  The two files you will need are these:

- 7.1.1-TIV-TDI-FP0004.zip
- TDI_GP_E_V7.1.1_WIN-X86_64.zip

*VirtualBox* 

If installing on a virtual machine, be sure to create a shared folder for transferring files between the host and the virtual appliance.  On my system I created a shared folder called _shared_, and another shared folder that points to the root of the OP workspace called _openpages_.  The names are unimportant.

There are exported Windows VirtualBox VMs in _opserver.swg.usma.ibm.com/Share/Windows IE VM Images_ that can be used for the purpose of TDI development and testing.  The exported VM I use originates from the exported image _Windows 7 IE 9.ova_ from the aforementioned share folder.  Simply import that into VirtualBox as a new VM.  Be sure to configure the shared folders as described.  

*VirtualBox Network Settings* 

Also, you will need to access the internet from the VM, as you will be connecting to CCH.  You will also need to network to your OpenPages instance running on the Host OS (either directly on the Host OS or in a Docker instance).  If you are running OpenPages on a remote server via the IBM internal network, then be sure to configure a Bridged network connection.  This https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/Wa37f5439c5fa_480b_92fb_66b4f71bcc50/page/VirtualBox%20Network%20Settings%20for%20OpenPages%20Development[wiki post] describes the VirtualBox networking setup required for OpenPages development and is applicable here as long as the OpenPages installation is on the Host OS (including Docker).  Follow the directions for setting up a _Host Only_ and _NAT Network_.  A bridged adapter will give your VM an actual ip address that can be accessed anywhere on the local network, and will make available to the virtual machine other machines on the same network.

As these instructions are being written, the following network adapters have been established:

1. Adapter 1 - Bridged Adapter - attached to en4: Thunderbolt Ethernet
2. Adapter 2 - Host-only Adapter - IPv4 Address: 192.168.59.100
3. Adapter 3 - NAT Network, Network CIDR: 10.0.2.0/24

Start the Windows 7 VM and check ip configuration by typing _ipconfig_ from the powershell.  You will see three ethernet adapters, listed in reverse order from how they match up to the adapters created in the previous step.  The names of these ethernet connections are:

- _Ethernet adapter Local Area Connection_ - Bridged (Adapter 1)
- _Ethernet adapter Local Area Connection 2_ - Host-only (Adapter 2)
- _Ethernet adapter Local Area Connection 3_ - NAT Network (Adapter 3)

**Bridged Adapter**


```
ipconfig 

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : usma.ibm.com
   IPv6 Address. . . . . . . . . . . : 2620:1f7:807:870::1:17b
   IPv6 Address. . . . . . . . . . . : 2620:1f7:807:870::1:27b
   Link-local IPv6 Address . . . . . : fe80::5d4b:18ab:2000:7939%11
   IPv4 Address. . . . . . . . . . . : 9.32.70.214
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : fe80::2%11
                                       fe80::1%11
                                       9.32.70.1
```

The bridged adapter is assigned a real IPv4 address that can be accessed from any system on the network.  Test this connection by pinging it from the Host OS:

```
js-macbook-pro:7.devenv sellis$ ping 9.32.70.214
PING 9.32.70.214 (9.32.70.214): 56 data bytes
64 bytes from 9.32.70.214: icmp_seq=0 ttl=128 time=0.436 ms
64 bytes from 9.32.70.214: icmp_seq=1 ttl=128 time=0.427 ms
64 bytes from 9.32.70.214: icmp_seq=2 ttl=128 time=0.399 ms
```

If ping does not work, then you may have a firewall issue on the Windows OS.  Try turning off the firewall, or create an exception in the firewall to allow incoming requests on that address.

**Host-Only Adapter**

The host-only adapter is a private connection that allows direct access to the Windows 7 VM through a static IP address that we have decided will be _192.168.59.100_.  That's the address we assigned when we created the network adapter in VirtualBox, but the address has to also be configured directly in Windows before it will take effect.  Try _ipconfig_ now and you will see that the ip address is not what we intendip:

```
Ethernet adapter Local Area Connection 2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::9407:e95d:b7b8:405d%13
   Autoconfiguration IPv4 Address. . : 169.254.64.93
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
```

To assign the static ip address, do the following:

- Open the control panel and navigate to _Network and Sharing Center_
- Click on the link for _Local Area Connection 2_
- Press the _Properties_ button.
- Select _Internet Protocol Version 4 (TCP/IPv4)_ and click on _Properties_
- Select the radio button _Use the following IP address:_
- Enter the following:
  * ip address: _192.168.59.100_
  * subnet mask: _255.255.255.0_
  * default gateway: _192.168.59.1_
  * Leave all DNS server addresses blank
- Shut down and restart Windows

If after reboot the ip address still is not the assigned value, then type the following:

```
PS C:\Windows\system32> netsh interface ipv4 show inter

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  1          50  4294967295  connected     Loopback Pseudo-Interface 1
 11          10        1500  connected     Local Area Connection
 13          10        1500  connected     Local Area Connection 2
 16          10        1500  connected     Local Area Connection 3
```

The index value of _Local Area Connection 2_ is 13, and is used in the following command that turns off autoconfiguration for that network interface:

```
netsh interface ipv4 set interface 13 dadtransmits=0 store=persistent
```

Reboot and check again with _ipconfig_:

```
Ethernet adapter Local Area Connection 2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::9407:e95d:b7b8:405d%13
   IPv4 Address. . . . . . . . . . . : 192.168.59.100
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.59.1
```

Who'd have dreamed it could be so simple?

**TDI Installation**

- Copy the downloaded TDI zip files to a local folder on the Windows VM and extract them. 
- In the _TDI_GP_E_V7.1.1_WIN-X86_64_ folder (created via extraction), execute _Launchpad.exe_
- Select _Install IBM Tivoli Directory Integrator_ then click the link to launch the product installation.



Copy the TDI zip files to the shared folder and 

- Fastmap import _UCF Entities.xlsx_ from grc_sdi_integrations/ucf_integration/support
- Might have to run ObjectManager on req-op-config.xml

