= UCF TDI Developer Setup =

https://www.ibm.com/support/knowledgecenter/SSFUEU_7.3.0/com.ibm.swg.ba.cognos.op_installation_guide.7.3.0.doc/c_op_ig_ucf_instl.html[Official Docs]

*Introduction*

OpenPages integrates with https://cch.commoncontrolshub.com[UCF Common Controls Hub] (referred to hereafter as CCH) to import Authority Documents, Citations and Controls using assembly lines as implemented in TDI (Tivoli Directory Integrator).  UCF stands for Unified Compliance Framework.

In a nutshell, CCH determines commonality amongst all controls across all industry authority documents and combines all of these controls into a single control, then references these common controls across all authority documents instead of duplicating them.  This greatly reduces the amount of time organizations need to spend during compliance.  Once the conditions of a control have been satisfied once, the conditions are satisfied for any and all processes that share that same control.

OpenPages has different object type names for the CCH types that are being imported.  The following list shows first the CCH type name and its OpenPages equivalent:

- Authority Document -> Mandate
- Citation -> SubMandate
- Control -> Requirement

The process of importing CCH objects into OpenPages begins with executing custom assembly lines in TDI.  To do this, you first need to install TDI on Windows.  If you are using a Mac, then this will describe how to install TDI using VirtualBox.

*The source code*

The TDI assembly line that integrates OP and CCH lives in RTC in _<workspace_root>/grc_sdi_integrations/ucf_integration_.  There you will find a README.txt that describes some of the steps that will be reproduced here.  Once TDI is installed this location will be accessed to import the assembly lines and import or update existing Mandates, SubMandates and Requirements.

*Installation*

The TDI installation files are included with the OP installation media, and can be found at _opserver.swg.usma.ibm.com/Share/TDI-7.1.1_.  The two files you will need are these:

- 7.1.1-TIV-TDI-FP0004.zip
- TDI_GP_E_V7.1.1_WIN-X86_64.zip

*VirtualBox* 

If installing on a virtual machine, be sure to create a shared folder for transferring files between the host and the virtual appliance.  On my system I created a shared folder called _shared_, and another shared folder that points to the root of the OP workspace called _openpages_.  The names are unimportant.

There are exported Windows VirtualBox VMs in _opserver.swg.usma.ibm.com/Share/Windows IE VM Images_ that can be used for the purpose of TDI development and testing.  The exported VM I use originates from the exported image _Windows Server 2012 - IE 11.ova_ from the aforementioned share folder.  Simply import that into VirtualBox as a new VM.  Be sure to configure the shared folders as described.  

Also, you will need to access the internet from the VM, as you will be connecting to CCH.  You will also need to network to your OpenPages instance running on the Host OS (either directly on the Host OS or in a Docker instance).  If you are running OpenPages on a remote server via the IBM internal network, then be sure to configure a Bridged network connection.  This https://w3-connections.ibm.com/wikis/home?lang=en-us#!/wiki/Wa37f5439c5fa_480b_92fb_66b4f71bcc50/page/VirtualBox%20Network%20Settings%20for%20OpenPages%20Development[wiki post] describes the VirtualBox networking setup required for OpenPages development and is applicable here as long as the OpenPages installation is on the Host OS (including Docker).  Follow the directions for setting up a _Host Only_ and _NAT Network_.  A bridged adapter will give your VM an actual ip address that can be accessed anywhere on the local network, and will make available to the virtual machine other machines on the same network.

As these instructions are being written, the following network adapters have been established:

1. Adapter 1 - Bridged Adapter - attached to en4: Thunderbolt Ethernet
2. Adapter 2 - Host-only Adapter - IPv4 Address: 192.168.59.100
3. Adapter 3 - NAT Network, Network CIDR: 10.0.2.0/24



Copy the TDI zip files to the shared folder and 

- Fastmap import _UCF Entities.xlsx_ from grc_sdi_integrations/ucf_integration/support
- Might have to run ObjectManager on req-op-config.xml

