= GraphQL 
:hp-tags: learning

- http://graphql.org/code/[GraphQL]
- https://codepen.io/jackett_dad/pen/rpbvpX[Sandbox for testing GraphQL and React]
- https://gramps.js.org/[GrAMPS]
- https://github.com/gramps-graphql/gramps-express[GrAMPS Express on Github]

This was learned from a FED event that I called into https://mail.notes.na.collabserv.com/livemail/($Calendar)/0C5B627A96825A0685258219006A8E4B/?OpenDocument&ui=portal&PresetFields=s_ParentContentId;($Calendar)2,s_ViewName;(%24Calendar),s_InheritAttachment;false,ThisStartDate;20180123T153000Z,s_CalViewWindowName;VerseCalendarView,&sq=1&cb=16007-1275&ci=1&em=1&ciex=1[here]


- https://www.apollographql.com/docs/apollo-server/[Apollo GraphQL Server Tutorial]
- https://dev-blog.apollodata.com/tutorial-building-a-graphql-server-cddaa023c035?_ga=2.195483500.1110204313.1517429637-616723183.1517429637[Tutorial: How to build a GraphQL server]
- https://dev-blog.apollodata.com/navigating-your-transition-to-graphql-28a4dfa3acfb[Navigating your transition to GraphQL]
- https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b[Full Stack with React and GraphQL Tutorial]


I set up an account at Apollo.  Generated an API key that I use in the apollo-tutorial-kit project that followed along with the https://dev-blog.apollodata.com/tutorial-building-a-graphql-server-cddaa023c035?_ga=2.155113208.1110204313.1517429637-616723183.1517429637[tutorial] linked above.  https://engine.apollographql.com/service/scottellis64-1360[There] I can view the performance of the queries the application makes.


*February 1, 2018*

Did part one of the https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b[Full Stack Tutorial] and had to really juggle it around to get it to work.  This was only part 1 of the series.  Apollo has been updated since this was written.  Got it working by calling to the original tutorial and running the GraphQL server in the apollo-tutorial-kit IntelliJ project.  But for mocking, I finally got it to work with the help of the https://github.com/dacz/apollo-bridge-link-example/blob/master/src/apolloClient-fullymocked.js[apollo-bridge-link] sample project.  Apollo test utils seems to be out of date.

https://www.apollographql.com/docs/graphql-tools/mocking.html[Mocking tutorial].  