= Develop New UI Setup =

When updating the Docker environment to the latest snapshot build, be sure to bring down the current version with:

- ```docker-compose down -v```

Then to bring up the new version and to view the logs until everything is ready to go:

- ```docker-compose up -d```
- ```docker logs --follow 7devenv_opapp_1```

From root of _grc_app_ui_:

- ```git checkout develop```
- ```git pull```
- ```npm install```
- ```npm run install```

In _grc_app_ui/com.ibm.openpages.app_:

- ```./gradlew build```

The code in _com.ibm.openpages.app_ can be loaded into Eclipse so that whenever _opapps.ear_ is exported and installed over a current OpenPages deployment (in local Docker container as done in development), then a one-time step needs to executed in _grc_app_ui/com.ibm.openpages.app_:

- ```./gradlew eclipse```

To import _com.ibm.openpages.app_ into Eclipse as a module under the grc_opapps working set:

- In Eclipse, select the menu option _File->Import..._ 
- Choose _General->Existing Projects into Workspace_ and click _Next >_
- Select the root directory as _<grc-app-ui root>/com.ibm.openpages.app_
- Select the project _com.ibm.openpages.app_
- Check the option _Copy projects into workspace_
- Check on _Add project to working sets_ and choose _grc_opapps_
- Click _Finish_

If this is a fresh version of OpenPages, then deployment targets need to be executed to run _ObjectManager_, which in turn ensures the existence of strings and other OP artifacts needed by the new ui at runtime.  So from the root of  _grc_app_ui_:

- ```npm run deploy```
- ```npm run gulp deployJarOnly```

This looks to be building and deploying the Angular 2 application as well, and something in here is needed by the React UI in the area of i18n strings.  Not sure what exactly, but a runtime error occurs when invoking the front page of the ReactUI if this step isn't done.  

This target starts and stops the _opapp_ remote node at _/home/opuser/OP/OpenPages/profiles/opapp-OPNode1_ on the Docker container.

To start the ReactUI in development mode, type the following in the root of _grc_app_ui_:

- ```npm run react:start```

See the ReactUI at ```https://localhost:3334/grc```

Redeploy the exported _opapps.ear_ by typing:

```bash
ssh -l opuser -p 24022 localhost
~/shared-devopsworkspace/docker/7.devenv/redeployEAR.sh
```




